create table ticket_medidas (
    id bigint generated by default as identity primary key,
    numero_ticket varchar(40) not null unique,
    fecha_hora timestamp not null,
    patente varchar(20) not null,
    acoplado varchar(20),
    transportista varchar(120),
    chofer varchar(120),
    largo_metros decimal(10,2) not null,
    ancho_metros decimal(10,2) not null,
    alto_metros decimal(10,2) not null,
    observaciones varchar(500)
);